### PR TITLE
feat: add build for platform amd64, arm64

### PR DESCRIPTION
**Pull request by priesdelly**
add detail to the GitHub workflow file
- add build support arm64, amd64
- disable provenance

### CODE REVIEW

**Comment by vittee** [comment]
Looks good to me, but how to actually test this before merging into the development branch? any ideas?

**Comment by visualizeq** [comment]
LGTM. can we change target branch to [develop](https://github.com/seamless-medley/medley/tree/develop) first?

**Comment by priesdelly** [comment]
Can't edit this ticket
Just close this ticket and create a new one for the target branch to `develop` first.

**Comment by vittee** [comment]
> Can't edit this ticket Just close this ticket and create a new one for the target branch to `develop` first.

Merging into `deveop` branch would not work either, since the native module is hosted on the NPM registry, regradless of the development process.

**Comment by vittee** [comment]
I'm about to close this as it turns out that adding platform `linux/arm64` did not do the trick.
This will cause Docker Engine to use QEMU to build for the foreign platform/arch and resulting in much slower build in the build pipeline.

The other thing is that there is no `arm64` C++ module, if the Docker image is eventually built, it would not work.

You can see in this diffs here https://github.com/seamless-medley/medley/compare/b343234...74b9a42

The multi-platform image is now built and pushed to the registry, but I'm not adding the `latest` tag to it for now, need to test it in different places before doing that.

**Pull request closed without merging**
